---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "partnerlogoservice"
spec:
  ports:
    -
      name: "web"
      protocol: "TCP"
      port: 8080
  selector:
    name: "partnerlogoservice"
  type: "ClusterIP"
  sessionAffinity: "None"
---
kind: "DeploymentConfig"
apiVersion: "v1"
metadata:
  name: "partnerlogoservice"
spec:
  template:
    metadata:
      labels:
        name: "partnerlogoservice"
      annotations:
        app_version: 'latest'
    spec:
      containers:
        -
          name: "partnerlogoservice"
          image: "containers.cisco.com/it_cits_csas/partnerlogo-deploy_partnerlogoservice:__IMAGETAG__"
          ports:
            -
              containerPort: 8080
              protocol: "TCP"
          env:
            -
              name: "APP_NAME"
              value: "partnerlogoservice"
            -
              name: "CISCO_LC"
              value: "dev"
            -
              name: "NODE_TLS_REJECT_UNAUTHORIZED"
              value: "0"
          volumeMounts:
            -
              name: podinfo
              mountPath: /etc/metadata
              readOnly: false
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities: {}
            privileged: false
            
      volumes:
        -
          name: podinfo
          downwardAPI:
            items:
              -
                path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              -
                path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
      restartPolicy: "Always"
      dnsPolicy: "ClusterFirst"
  replicas: 1
  selector:
    name: "partnerlogoservice"
  triggers:
    -
      type: "ConfigChange"
  strategy:
    type: "Rolling"
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 300
      updatePeriodSeconds: 1
...
---
apiVersion: "v1"
kind: "Service"
metadata:
   name: "mysql-5-6"
   labels:
     name:  "mysql-5-6"
spec:
   ports:
    - 
     port: 3306
     targetPort: 3306
     protocol: "TCP"
   selector:
     name: "mysql-5-6"
...
---
apiVersion: "v1"
kind: "DeploymentConfig"
metadata:
  name: "mysql-5-6"
  labels:
    name: "mysql-5-6"
spec:
    replicas: 1
    revisionHistoryLimit: 5
    template:
        metadata:
          labels:
            name: "mysql-5-6"
        spec:    
            containers:
                    - name:  "mysql-5-6"
                      image: "containers.cisco.com/aws_managed/mysql-5.6"
                      resources:
                         limits:
                            memory: "1Gi"
                            cpu: "300m"
                         requests:
                            memory: "512Mi"
                            cpu: "200m"
                      ports:
                        - containerPort: 3306
                          protocol: "TCP"
                      env:
                        - name: MYSQL_DATABASE
                          value: partnerlogodb
                        - name: APP_NAME
                          value: partnerlogo-mysql
                        - name: MYSQL_USER
                          valueFrom:
                            secretKeyRef:
                              name: mysecret
                              key: username
                        - name: MYSQL_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mysecret
                              key: password
                        - name: MYSQL_ROOT_PASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: mysecretadmin
                              key: password

                      volumeMounts:
                      - mountPath: "/var/lib/mysql/data"
                        name: "mysql-persistent-storage"
            volumes:
             - name: "mysql-persistent-storage"
               persistentVolumeClaim:
                 claimName: "mysql-pv-claim"
...
